//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insertions
    {
        public int IdInsertion { get; set; }
        public string Description { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual Tenants Tenants { get; set; }
    }
}
