//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VaadBayitEntities : DbContext
    {
        public VaadBayitEntities()
            : base("name=VaadBayitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionVaad> CollectionVaad { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Frequencies> Frequencies { get; set; }
        public virtual DbSet<FrequencyObject> FrequencyObject { get; set; }
        public virtual DbSet<FrequencyOperator> FrequencyOperator { get; set; }
        public virtual DbSet<FrequencyType> FrequencyType { get; set; }
        public virtual DbSet<Insertions> Insertions { get; set; }
        public virtual DbSet<Professionals> Professionals { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<Tenants> Tenants { get; set; }
        public virtual DbSet<TypeOfProfessionals> TypeOfProfessionals { get; set; }
        public virtual DbSet<TypeOfTasks> TypeOfTasks { get; set; }
    }
}
