//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int IdTask { get; set; }
        public Nullable<int> TypeOfTask { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> FixedBy { get; set; }
        public string FixedCost { get; set; }
        public Nullable<System.DateTime> FixeDate { get; set; }
        public Nullable<int> IdExpense { get; set; }
        public Nullable<int> IdFrequency { get; set; }
    
        public virtual Expenses Expenses { get; set; }
        public virtual Frequencies Frequencies { get; set; }
        public virtual Professionals Professionals { get; set; }
        public virtual TypeOfTasks TypeOfTasks { get; set; }
    }
}
