//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int TenantCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Floor { get; set; }
        public int NumOfApartment { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string E_Mail { get; set; }
        public string Modifier { get; set; }
        public string Password { get; set; }
    }
}
