//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenants()
        {
            this.CollectionVaad = new HashSet<CollectionVaad>();
            this.Insertions = new HashSet<Insertions>();
        }
    
        public int TenantCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Floor { get; set; }
        public int NumOfApartment { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string E_Mail { get; set; }
        public string Modifier { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionVaad> CollectionVaad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insertions> Insertions { get; set; }
    }
}
